general:
  overwrite: false
  gmx_command: gmx
forcefield:
  name: charmm36m-mut
  index: 9
  custom_forcefields:
    1:
      name: a99SBdisp
      dir: a99SBdisp.ff
      path: /home/gxf1212/data/local_programs/mutff/a99SBdisp.ff
      source: GMXLIB
    2:
      name: amber14sb_OL15
      dir: amber14sb_OL15.ff
      path: /home/gxf1212/data/local_programs/mutff/amber14sb_OL15.ff
      source: GMXLIB
    3:
      name: amber14sbmut
      dir: amber14sbmut.ff
      path: /home/gxf1212/data/local_programs/mutff/amber14sbmut.ff
      source: GMXLIB
    4:
      name: amber99sb-star-ildn-bsc1-mut
      dir: amber99sb-star-ildn-bsc1-mut.ff
      path: /home/gxf1212/data/local_programs/mutff/amber99sb-star-ildn-bsc1-mut.ff
      source: GMXLIB
    5:
      name: amber99sb-star-ildn-dna-mut
      dir: amber99sb-star-ildn-dna-mut.ff
      path: /home/gxf1212/data/local_programs/mutff/amber99sb-star-ildn-dna-mut.ff
      source: GMXLIB
    6:
      name: amber99sb-star-ildn-mut
      dir: amber99sb-star-ildn-mut.ff
      path: /home/gxf1212/data/local_programs/mutff/amber99sb-star-ildn-mut.ff
      source: GMXLIB
    7:
      name: charmm22star-mut
      dir: charmm22star-mut.ff
      path: /home/gxf1212/data/local_programs/mutff/charmm22star-mut.ff
      source: GMXLIB
    8:
      name: charmm36-jul2022
      dir: charmm36-jul2022.ff
      path: /home/gxf1212/data/local_programs/mutff/charmm36-jul2022.ff
      source: GMXLIB
    9:
      name: charmm36m-mut
      dir: charmm36m-mut.ff
      path: /home/gxf1212/data/local_programs/mutff/charmm36m-mut.ff
      source: GMXLIB
    10:
      name: oplsaam
      dir: oplsaam.ff
      path: /home/gxf1212/data/local_programs/mutff/oplsaam.ff
      source: GMXLIB
    11:
      name: amber03
      dir: amber03.ff
      path: /opt/gromacs/2024.4/share/gromacs/top/amber03.ff
      source: GROMACS installation
    12:
      name: amber94
      dir: amber94.ff
      path: /opt/gromacs/2024.4/share/gromacs/top/amber94.ff
      source: GROMACS installation
    13:
      name: amber96
      dir: amber96.ff
      path: /opt/gromacs/2024.4/share/gromacs/top/amber96.ff
      source: GROMACS installation
    14:
      name: amber99
      dir: amber99.ff
      path: /opt/gromacs/2024.4/share/gromacs/top/amber99.ff
      source: GROMACS installation
    15:
      name: amber99sb-ildn
      dir: amber99sb-ildn.ff
      path: /opt/gromacs/2024.4/share/gromacs/top/amber99sb-ildn.ff
      source: GROMACS installation
    16:
      name: amber99sb
      dir: amber99sb.ff
      path: /opt/gromacs/2024.4/share/gromacs/top/amber99sb.ff
      source: GROMACS installation
    17:
      name: amberGS
      dir: amberGS.ff
      path: /opt/gromacs/2024.4/share/gromacs/top/amberGS.ff
      source: GROMACS installation
    18:
      name: charmm27
      dir: charmm27.ff
      path: /opt/gromacs/2024.4/share/gromacs/top/charmm27.ff
      source: GROMACS installation
    19:
      name: gromos43a1
      dir: gromos43a1.ff
      path: /opt/gromacs/2024.4/share/gromacs/top/gromos43a1.ff
      source: GROMACS installation
    20:
      name: gromos43a2
      dir: gromos43a2.ff
      path: /opt/gromacs/2024.4/share/gromacs/top/gromos43a2.ff
      source: GROMACS installation
    21:
      name: gromos45a3
      dir: gromos45a3.ff
      path: /opt/gromacs/2024.4/share/gromacs/top/gromos45a3.ff
      source: GROMACS installation
    22:
      name: gromos53a5
      dir: gromos53a5.ff
      path: /opt/gromacs/2024.4/share/gromacs/top/gromos53a5.ff
      source: GROMACS installation
    23:
      name: gromos53a6
      dir: gromos53a6.ff
      path: /opt/gromacs/2024.4/share/gromacs/top/gromos53a6.ff
      source: GROMACS installation
    24:
      name: gromos54a7
      dir: gromos54a7.ff
      path: /opt/gromacs/2024.4/share/gromacs/top/gromos54a7.ff
      source: GROMACS installation
    25:
      name: oplsaa
      dir: oplsaa.ff
      path: /opt/gromacs/2024.4/share/gromacs/top/oplsaa.ff
      source: GROMACS installation
water_model:
  name: tip3p
  index: 1
  custom_water_models:
    1:
      name: tip3p
      label: TIP3P
      description: TIP 3-point, recommended, by default uses CHARMM TIP3 with LJ on
        H
    2:
      name: tip4p
      label: TIP4P
      description: TIP 4-point
    3:
      name: tip5p
      label: TIP5P
      description: TIP 5-point
    4:
      name: spc
      label: SPC
      description: simple point charge
    5:
      name: spce
      label: SPC/E
      description: extended simple point charge
box:
  distance: 1.5
  shape: cubic
  center: true
simulation:
  temperature: 310
  pressure: 1.0
  pH: 7.0
  ligand_charge: 0
  production_time_ns: 10.0
  dt: 0.002
  equilibration_nvt_time_ps: 500
  equilibration_npt_time_ps: 500
ions:
  neutral: true
  concentration: 0.15
  positive_ion: NA
  negative_ion: CL
constraints:
  algorithm: lincs
  type: h-bonds
  lincs_iter: 1
  lincs_order: 4
energy_minimization:
  integrator: steep
  emtol: 200.0
  emstep: 0.01
  nsteps: 10000
output:
  trajectory_interval_ps: 500
  energy_interval_ps: 10
  log_interval_ps: 10
  compressed_trajectory: true
electrostatics:
  coulombtype: PME
  rcoulomb: 1.0
  pme_order: 4
  fourierspacing: 0.16
vdw:
  rvdw: 1.0
  dispcorr: EnerPres
temperature_coupling:
  tcoupl: V-rescale
  tc_grps:
  - Protein
  - Non-Protein
  tau_t:
  - 0.1
  - 0.1
pressure_coupling:
  pcoupl: C-rescale
  pcoupltype: isotropic
  tau_p: 1.0
  compressibility: 4.5e-05
ligand_forcefield:
  type: mmff
  charge: 0
