#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
File I/O module for PRISM-FEP

This module handles reading PRISM-generated files (ITP and GRO) for FEP processing.
"""

from typing import List
import numpy as np
from prism.gaussian.utils import normalize_element_symbol
from prism.fep.core.mapping import Atom


def read_ligand_from_prism(itp_file: str, gro_file: str) -> List[Atom]:
    """
    Read ligand information from PRISM-generated ITP and GRO files.

    This function reads atomic information from GROMACS ITP and GRO files
    generated by PRISM's force field parameterization.

    Parameters
    ----------
    itp_file : str
        Path to GROMACS ITP file containing atom types, charges, and parameters
    gro_file : str
        Path to GROMACS GRO file containing atomic coordinates

    Returns
    -------
    List[Atom]
        List of Atom objects containing coordinates, charges, types, etc.

    Notes
    -----
    ITP file format ([ atoms ] section):
        nr type resnr residue atom cgnr charge mass typeB chargeB massB

    GRO file format:
        residue_id residue_name atom_name atom_id x y z

    Coordinate conversion:
        GRO files use nanometers (nm), this function converts to Angstroms (Å)
    """
    # Step 1: Read ITP file to get atom types and charges
    atoms_data = []
    with open(itp_file, "r") as f:
        in_atoms_section = False
        for line in f:
            line_stripped = line.strip()

            # Find [ atoms ] section
            if "[ atoms ]" in line.lower():
                in_atoms_section = True
                continue
            # Exit section when hitting next section
            elif line_stripped.startswith("[") and in_atoms_section:
                in_atoms_section = False
                continue

            # Parse atom lines
            if in_atoms_section and line_stripped and not line_stripped.startswith(";"):
                parts = line_stripped.split()
                if len(parts) >= 7:
                    try:
                        atom_id = int(parts[0])
                        atom_type = parts[1]
                        atom_name = parts[4]
                        charge = float(parts[6])
                        atoms_data.append({"id": atom_id, "name": atom_name, "type": atom_type, "charge": charge})
                    except (ValueError, IndexError) as e:
                        # Skip malformed lines
                        continue

    # Step 2: Read GRO file to get coordinates
    coords = {}
    with open(gro_file, "r") as f:
        lines = f.readlines()

        # GRO format:
        # Line 1: title
        # Line 2: atom count
        # Line 3+: atom_id residue_name residue_name atom_id x y z
        # Last line: box dimensions

        for line in lines[2:-1]:  # Skip title and box line
            parts = line.split()
            if len(parts) >= 7:
                try:
                    atom_id = int(parts[2])
                    # GRO coordinates are in nm, convert to Angstroms (×10)
                    x = float(parts[3]) * 10.0
                    y = float(parts[4]) * 10.0
                    z = float(parts[5]) * 10.0
                    coords[atom_id] = np.array([x, y, z])
                except (ValueError, IndexError):
                    continue

    # Step 3: Merge data into Atom objects
    atoms = []
    for atom_data in atoms_data:
        atom_id = atom_data["id"]
        element = _extract_element(atom_data["name"])

        # Get coordinate, use default if not found
        coord = coords.get(atom_id, np.array([0.0, 0.0, 0.0]))

        atoms.append(
            Atom(
                name=atom_data["name"],
                element=element,
                coord=coord,
                charge=atom_data["charge"],
                atom_type=atom_data["type"],
                index=atom_id,
            )
        )

    return atoms


def _extract_element(atom_name: str) -> str:
    """
    Extract element symbol from atom name.

    Parameters
    ----------
    atom_name : str
        Atom name (e.g., 'C1', 'H2', 'N3', 'CA', 'HB1')

    Returns
    -------
    str
        Element symbol (e.g., 'C', 'H', 'N')

    Examples
    --------
    >>> _extract_element('C1')
    'C'
    >>> _extract_element('HB1')
    'H'
    >>> _extract_element('CA')
    'C'
    """
    # Remove digits, keep only letters
    element = "".join(c for c in atom_name if c.isalpha())

    # Normalize element symbol (first uppercase, rest lowercase)
    if element:
        return normalize_element_symbol(element)

    # Default to carbon if cannot determine
    return "C"


def read_mol2_atoms(mol2_file: str) -> List[Atom]:
    """
    Read atomic information from MOL2 file (for quick testing).

    This function provides a direct path for testing without requiring
    PRISM parameterization. For production use, prefer read_ligand_from_prism().

    Parameters
    ----------
    mol2_file : str
        Path to MOL2 file

    Returns
    -------
    List[Atom]
        List of Atom objects

    Notes
    -----
    MOL2 file format (@<TRIPOS>ATOM section):
        atom_id atom_name x y z atom_type subst_id subst_name charge

    This function reuses PRISM's mol2 parsing logic from gaussian/utils.py
    """
    atoms = []
    in_atom_section = False

    with open(mol2_file, "r") as f:
        for line in f:
            if line.startswith("@<TRIPOS>ATOM"):
                in_atom_section = True
                continue
            elif line.startswith("@<TRIPOS>") and in_atom_section:
                break

            if in_atom_section and line.strip():
                parts = line.split()
                if len(parts) >= 9:
                    try:
                        atom_id = int(parts[0])
                        name = parts[1]
                        x, y, z = float(parts[2]), float(parts[3]), float(parts[4])
                        atom_type = parts[5]
                        charge = float(parts[8])

                        # Extract element from atom_type
                        if "." in atom_type:
                            element = normalize_element_symbol(atom_type.split(".")[0])
                        else:
                            element = normalize_element_symbol(atom_type)

                        atoms.append(
                            Atom(
                                name=name,
                                element=element,
                                coord=np.array([x, y, z]),
                                charge=charge,
                                atom_type=atom_type,
                                index=atom_id,
                            )
                        )
                    except (ValueError, IndexError) as e:
                        continue

    return atoms


def read_cgenff_system(rtf_file: str, pdb_file: str) -> List[Atom]:
    """
    Read ligand with CGenFF parameters from RTF and coordinates from PDB

    This is the preferred method for FEP calculations as it uses
    force field-specific atom types and charges.

    Parameters
    ----------
    rtf_file : str
        CGenFF RTF file path (atom types and charges)
    pdb_file : str
        PDB file path (aligned coordinates)

    Returns
    -------
    List[Atom]
        List of Atom objects with complete information

    Examples
    --------
    >>> atoms = read_cgenff_system('ligand.rtf', 'ligand.pdb')
    >>> mapper = DistanceAtomMapper()
    >>> mapping = mapper.map(atoms, other_atoms)
    """
    # Read RTF file for atom types and charges
    rtf_data = {}
    with open(rtf_file, "r") as f:
        for line in f:
            if line.strip().startswith("ATOM"):
                parts = line.split()
                name = parts[1]
                atom_type = parts[2]
                charge = float(parts[3])
                rtf_data[name] = {"type": atom_type, "charge": charge}

    # Read PDB file for coordinates
    atoms = []
    atom_id = 0
    with open(pdb_file, "r") as f:
        for line in f:
            if line.startswith("ATOM") or line.startswith("HETATM"):
                atom_name = line[12:16].strip()

                # Only process atoms that exist in RTF
                if atom_name not in rtf_data:
                    continue

                atom_id += 1
                # Try to get element from PDB column 77-78, but fallback to atom name extraction
                # Many PDB files don't have the element column properly formatted
                element_from_pdb = line[76:78].strip() if len(line) > 77 else ""
                if element_from_pdb and element_from_pdb.isalpha():
                    element = element_from_pdb.upper()
                else:
                    # Extract element from atom name (F1 -> F, C10 -> C, etc.)
                    element = _extract_element(atom_name)

                x = float(line[30:38].strip())
                y = float(line[38:46].strip())
                z = float(line[46:54].strip())

                atoms.append(
                    Atom(
                        name=atom_name,
                        element=element,
                        coord=np.array([x, y, z]),
                        charge=rtf_data[atom_name]["charge"],
                        atom_type=rtf_data[atom_name]["type"],
                        index=atom_id,
                    )
                )

    return atoms
