#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
File I/O module for PRISM-FEP

This module handles reading PRISM-generated files (ITP and GRO) for FEP processing.
"""

from typing import List, Optional, Tuple, Dict, Any, Set
import numpy as np
import re
from prism.gaussian.utils import normalize_element_symbol
from prism.fep.core.mapping import Atom


def read_ligand_from_prism(itp_file: str, gro_file: str, state: Optional[str] = None) -> List[Atom]:
    """
    Read ligand information from PRISM-generated ITP and GRO files.

    This function reads atomic information from GROMACS ITP and GRO files
    generated by PRISM's force field parameterization.

    Parameters
    ----------
    itp_file : str
        Path to GROMACS ITP file containing atom types, charges, and parameters.
    gro_file : str
        Path to GROMACS GRO file containing atomic coordinates.
    state : str, optional
        Hybrid-topology state selector: ``"a"`` or ``"b"``. When omitted,
        regular ligand ITP files are read normally. When provided for a hybrid
        ITP, dummy atoms are filtered out and state-B atom names are taken from
        ``; name_b (state B): ...`` comments when present.

    Returns
    -------
    List[Atom]
        List of Atom objects containing coordinates, charges, types, etc.

    Notes
    -----
    ITP file format ([ atoms ] section):
        nr type resnr residue atom cgnr charge mass typeB chargeB massB

    GRO file format:
        residue_id residue_name atom_name atom_id x y z

    Coordinate conversion:
        GRO files use nanometers (nm), this function converts to Angstroms (Å)
    """
    normalized_state = state.lower() if state is not None else None
    if normalized_state not in {None, "a", "b"}:
        raise ValueError(f"Unsupported state: {state}. Expected None, 'a', or 'b'.")

    atoms_data = _parse_itp_atoms(itp_file, capture_state_b_names=normalized_state == "b")
    selected_atoms = _select_state_atoms(atoms_data, normalized_state)

    coords_by_id, coords_by_name, elements_by_id = _load_structure_coordinates(gro_file)

    atoms = []
    for atom_data in selected_atoms:
        atom_id = atom_data["id"]
        atom_name = atom_data["name"]

        # Use ITP atom names as the source of truth for element identity.
        # Force-field generators may reorder atoms while keeping names/types consistent,
        # so structure-file atom indices are not reliable for element assignment.
        element = _extract_element(atom_name)

        coord = coords_by_id.get(atom_id, coords_by_name.get(atom_name, np.array([0.0, 0.0, 0.0])))

        atoms.append(
            Atom(
                name=atom_name,
                element=element,
                coord=coord,
                charge=atom_data["charge"],
                atom_type=atom_data["type"],
                index=atom_id,
            )
        )

    return atoms


def _load_structure_coordinates(
    structure_file: str,
) -> Tuple[Dict[int, np.ndarray], Dict[str, np.ndarray], Dict[int, str]]:
    """Load coordinates from PDB, MOL2, or GRO into shared lookup tables."""
    coords_by_id: Dict[int, np.ndarray] = {}
    coords_by_name: Dict[str, np.ndarray] = {}
    elements_by_id: Dict[int, str] = {}

    with open(structure_file, "r") as handle:
        header_lines = [handle.readline().strip() for _ in range(3)]

    first_nonempty = next((line for line in header_lines if line), "")
    is_pdb = (
        first_nonempty.startswith("ATOM") or first_nonempty.startswith("HETATM") or first_nonempty.startswith("REMARK")
    )
    is_mol2 = any(line.startswith("@<TRIPOS>MOLECULE") for line in header_lines)

    if is_pdb:
        with open(structure_file, "r") as handle:
            for line in handle:
                if not (line.startswith("ATOM") or line.startswith("HETATM")):
                    continue
                try:
                    atom_name = line[12:16].strip()
                    atom_id = int(line[6:11].strip())
                    x = float(line[30:38].strip())
                    y = float(line[38:46].strip())
                    z = float(line[46:54].strip())
                except (ValueError, IndexError):
                    continue

                coord = np.array([x, y, z])
                coords_by_id[atom_id] = coord
                coords_by_name[atom_name] = coord
                elements_by_id[atom_id] = _extract_element(atom_name)
        return coords_by_id, coords_by_name, elements_by_id

    if is_mol2:
        with open(structure_file, "r") as handle:
            in_atom_section = False
            for line in handle:
                stripped = line.strip()
                if stripped.startswith("@<TRIPOS>ATOM"):
                    in_atom_section = True
                    continue
                if stripped.startswith("@<TRIPOS>") and in_atom_section:
                    break
                if not in_atom_section or not stripped:
                    continue

                parts = stripped.split()
                if len(parts) < 6:
                    continue
                try:
                    atom_id = int(parts[0])
                    atom_name = parts[1]
                    x = float(parts[2])
                    y = float(parts[3])
                    z = float(parts[4])
                except ValueError:
                    continue

                atom_type_field = parts[5]
                # Extract element from atom name (more reliable than atom type field)
                element_symbol = _extract_element(atom_name)
                coord = np.array([x, y, z])
                coords_by_id[atom_id] = coord
                coords_by_name[atom_name] = coord
                elements_by_id[atom_id] = element_symbol
        return coords_by_id, coords_by_name, elements_by_id

    with open(structure_file, "r") as handle:
        lines = handle.readlines()

    for line in lines[2:-1]:
        parts = line.split()
        if len(parts) >= 7:
            atom_name = parts[2]
            atom_id = int(parts[3])
            x = float(parts[4]) * 10.0
            y = float(parts[5]) * 10.0
            z = float(parts[6]) * 10.0
        elif len(parts) >= 6:
            atom_name = parts[1]
            atom_id = int(parts[2])
            x = float(parts[3]) * 10.0
            y = float(parts[4]) * 10.0
            z = float(parts[5]) * 10.0
        else:
            continue

        try:
            coord = np.array([x, y, z])
            coords_by_id[atom_id] = coord
            coords_by_name[atom_name] = coord
        except (ValueError, IndexError):
            continue

    return coords_by_id, coords_by_name, elements_by_id


def _read_mol2_atom_names(mol2_file: Optional[str]) -> Tuple[Optional[List[str]], Set[str]]:
    """Return MOL2 atom order and name set for optional sorting/conflict handling."""
    if not mol2_file:
        return None, set()

    atom_order: List[str] = []
    atom_names: Set[str] = set()
    with open(mol2_file, "r") as handle:
        in_atoms = False
        for line in handle:
            if line.startswith("@<TRIPOS>ATOM"):
                in_atoms = True
                continue
            if line.startswith("@") and in_atoms:
                break
            if not in_atoms:
                continue
            parts = line.split()
            if len(parts) >= 2:
                atom_name = parts[1]
                atom_order.append(atom_name)
                atom_names.add(atom_name)
    return atom_order, atom_names


def _parse_itp_atoms(itp_file: str, capture_state_b_names: bool = False) -> List[Dict[str, Any]]:
    """Parse the ``[ atoms ]`` block of a ligand ITP into a neutral intermediate form."""
    atoms_data: List[Dict[str, Any]] = []
    pending_name_b = None

    with open(itp_file, "r") as handle:
        in_atoms_section = False
        for line in handle:
            line_stripped = line.strip()

            if "[ atoms ]" in line.lower():
                in_atoms_section = True
                continue
            if line_stripped.startswith("[") and in_atoms_section:
                in_atoms_section = False
                continue
            if not in_atoms_section:
                continue

            if line_stripped.startswith(";"):
                if capture_state_b_names and "name_b (state B):" in line_stripped:
                    pending_name_b = line_stripped.split("name_b (state B):", 1)[1].strip()
                continue
            if not line_stripped:
                continue

            comment_idx = line_stripped.find(";")
            if comment_idx != -1:
                line_stripped = line_stripped[:comment_idx].strip()

            parts = line_stripped.split()
            if len(parts) < 8:
                continue

            try:
                atom_record = {
                    "id": int(parts[0]),
                    "name": parts[4],
                    "type_a": parts[1],
                    "charge_a": float(parts[6]),
                    "type_b": parts[8] if len(parts) >= 11 else None,
                    "charge_b": float(parts[9]) if len(parts) >= 11 else None,
                    "name_b": pending_name_b,
                }
            except (ValueError, IndexError):
                pending_name_b = None
                continue

            atoms_data.append(atom_record)
            pending_name_b = None

    return atoms_data


def _select_state_atoms(atoms_data: List[Dict[str, Any]], state: Optional[str]) -> List[Dict[str, Any]]:
    """Project parsed hybrid-ITP atoms onto a requested state representation."""
    if state is None:
        return [
            {
                "id": atom["id"],
                "name": atom["name"],
                "type": atom["type_a"],
                "charge": atom["charge_a"],
            }
            for atom in atoms_data
        ]

    all_atom_names = {atom["name"] for atom in atoms_data}
    selected_atoms: List[Dict[str, Any]] = []

    for atom in atoms_data:
        atom_name = atom["name"]
        atom_type_a = atom["type_a"]
        atom_type_b = atom["type_b"]

        if state == "a":
            if atom_type_a.startswith("DUM"):
                continue
            selected_atoms.append(
                {
                    "id": atom["id"],
                    "name": atom_name,
                    "type": atom_type_a,
                    "charge": atom["charge_a"],
                }
            )
            continue

        if atom_type_b is not None:
            if atom_type_b.startswith("DUM"):
                continue
            selected_atoms.append(
                {
                    "id": atom["id"],
                    "name": atom["name_b"] or atom_name,
                    "type": atom_type_b,
                    "charge": atom["charge_b"],
                }
            )
            continue

        if atom_type_a.startswith("DUM"):
            continue

        # FEbuilder may store the B-state identity in comments even when a
        # separate `XXXB` atom exists in the hybrid topology. That explicit
        # comment should win over the suffix heuristic.
        if atom["name_b"]:
            selected_atoms.append(
                {
                    "id": atom["id"],
                    "name": atom["name_b"],
                    "type": atom_type_a,
                    "charge": atom["charge_a"],
                }
            )
            continue

        if f"{atom_name}B" in all_atom_names:
            continue

        selected_atoms.append(
            {
                "id": atom["id"],
                "name": atom_name,
                "type": atom_type_a,
                "charge": atom["charge_a"],
            }
        )

    return selected_atoms


def _extract_element(atom_name: str) -> str:
    """
    Extract element symbol from atom name.

    Parameters
    ----------
    atom_name : str
        Atom name (e.g., 'C1', 'H2', 'N3', 'CA', 'HB1', 'FE', 'Cl')

    Returns
    -------
    str
        Element symbol (e.g., 'C', 'H', 'N', 'Fe', 'Cl')

    Examples
    --------
    >>> _extract_element('C1')
    'C'
    >>> _extract_element('HB1')
    'H'
    >>> _extract_element('CA')
    'C'
    >>> _extract_element('FE')
    'Fe'
    >>> _extract_element('Cl')
    'Cl'
    """
    # Remove digits, keep only letters
    letters = "".join(c for c in atom_name if c.isalpha())

    if not letters:
        return "C"  # Default to carbon

    # For biomolecular atom names (PDB/GROMACS style):
    # - Atom names are typically 1-4 characters
    # - Element is ALWAYS the first letter
    # - Second letter (if present) is typically:
    #   - Uppercase: position code (CA, CB, CG, CD, CE, CZ = carbons)
    #   - Lowercase: part of two-letter element ONLY for rare elements (Fe, Cl, Br, etc.)

    # Common two-letter elements in drug-like molecules that use lowercase
    # These are the ONLY cases where the second letter matters
    organic_two_letter_elements = {"Cl", "Br", "Fe", "Mg", "Ca", "Zn", "Cu", "Mn", "Se", "Si"}

    # Check if this could be a two-letter element
    if len(letters) >= 2:
        # Check case pattern: two-letter elements are like "Cl", "Fe" (upper + lower)
        if letters[0].isupper() and letters[1].islower():
            candidate = letters[0] + letters[1]
            if candidate in organic_two_letter_elements:
                return candidate

    # Default: use first letter only (C, H, N, O, S, P, F, etc.)
    return letters[0].upper()


def read_mol2_atoms(mol2_file: str) -> List[Atom]:
    """
    Read atomic information from MOL2 file (for quick testing).

    This function provides a direct path for testing without requiring
    PRISM parameterization. For production use, prefer read_ligand_from_prism().

    Parameters
    ----------
    mol2_file : str
        Path to MOL2 file

    Returns
    -------
    List[Atom]
        List of Atom objects

    Notes
    -----
    MOL2 file format (@<TRIPOS>ATOM section):
        atom_id atom_name x y z atom_type subst_id subst_name charge

    This function reuses PRISM's mol2 parsing logic from gaussian/utils.py
    """
    atoms = []
    in_atom_section = False

    with open(mol2_file, "r") as f:
        for line in f:
            if line.startswith("@<TRIPOS>ATOM"):
                in_atom_section = True
                continue
            elif line.startswith("@<TRIPOS>") and in_atom_section:
                break

            if in_atom_section and line.strip():
                parts = line.split()
                if len(parts) >= 9:
                    try:
                        atom_id = int(parts[0])
                        name = parts[1]
                        x, y, z = float(parts[2]), float(parts[3]), float(parts[4])
                        atom_type = parts[5]
                        charge = float(parts[8])

                        # Extract element from atom_type
                        if "." in atom_type:
                            element = normalize_element_symbol(atom_type.split(".")[0])
                        else:
                            element = normalize_element_symbol(atom_type)

                        atoms.append(
                            Atom(
                                name=name,
                                element=element,
                                coord=np.array([x, y, z]),
                                charge=charge,
                                atom_type=atom_type,
                                index=atom_id,
                            )
                        )
                    except (ValueError, IndexError) as e:
                        continue

    return atoms


def read_rtf_for_fep(rtf_file: str, pdb_file: str) -> List[Atom]:
    """
    Read ligand from RTF (atom types/charges) and PDB (coordinates) for FEP mapping

    This function is specifically designed for FEP calculations, reading
    RTF files (from CGenFF, MATCH, SwissParam, etc.) and combining with
    PDB coordinates to create Atom objects for mapping.

    Parameters
    ----------
    rtf_file : str
        RTF file path (atom types and charges)
    pdb_file : str
        PDB file path (aligned coordinates)

    Returns
    -------
    List[Atom]
        List of Atom objects with complete information

    Examples
    --------
    >>> atoms = read_rtf_for_fep('ligand.rtf', 'ligand.pdb')
    >>> mapper = DistanceAtomMapper()
    >>> mapping = mapper.map(atoms, other_atoms)
    """
    # Read RTF file for atom types and charges
    rtf_data = {}
    with open(rtf_file, "r") as f:
        for line in f:
            if line.strip().startswith("ATOM"):
                parts = line.split()
                name = parts[1]
                atom_type = parts[2]
                charge = float(parts[3])
                rtf_data[name] = {"type": atom_type, "charge": charge}

    # Read PDB file for coordinates
    atoms = []
    atom_id = 0
    with open(pdb_file, "r") as f:
        for line in f:
            if line.startswith("ATOM") or line.startswith("HETATM"):
                atom_name = line[12:16].strip()

                # Only process atoms that exist in RTF
                if atom_name not in rtf_data:
                    continue

                atom_id += 1
                # Try to get element from PDB column 77-78, but fallback to atom name extraction
                # Many PDB files don't have the element column properly formatted
                element_from_pdb = line[76:78].strip() if len(line) > 77 else ""
                if element_from_pdb and element_from_pdb.isalpha():
                    element = element_from_pdb.upper()
                else:
                    # Extract element from atom name (F1 -> F, C10 -> C, etc.)
                    element = _extract_element(atom_name)

                x = float(line[30:38].strip())
                y = float(line[38:46].strip())
                z = float(line[46:54].strip())

                atoms.append(
                    Atom(
                        name=atom_name,
                        element=element,
                        coord=np.array([x, y, z]),
                        charge=rtf_data[atom_name]["charge"],
                        atom_type=rtf_data[atom_name]["type"],
                        index=atom_id,
                    )
                )

    return atoms


def write_ligand_to_pdb(atoms: List[Atom], output_pdb: str, residue_name: str = "LIG") -> None:
    """
    Write Atom objects to PDB format file.

    This function is the counterpart to read_ligand_from_prism(), converting
    Atom objects back to PDB format for visualization (HTML/PNG) or other uses.

    Parameters
    ----------
    atoms : List[Atom]
        List of Atom objects to write
    output_pdb : str
        Path to output PDB file
    residue_name : str, optional
        Residue name to use in PDB file (default: "LIG")

    Notes
    -----
    PDB ATOM record format (columns):
        1-6:   "ATOM" (record name)
        7-11:  Atom serial number
        13-16: Atom name
        17:    Alternate location (blank)
        18-20: Residue name (right-justified)
        22:    Chain identifier (blank)
        23-26: Residue sequence number
        27:    Insertion code (blank)
        31-38: X coordinate (Å, right-justified, 8.3 format)
        39-46: Y coordinate (Å, right-justified, 8.3 format)
        47-54: Z coordinate (Å, right-justified, 8.3 format)
        55-60: Occupancy (default 1.00)
        61-66: Temperature factor (default 0.00)

    Examples
    --------
    >>> atoms = read_ligand_from_prism("LIG.itp", "LIG.gro")
    >>> write_ligand_to_pdb(atoms, "output.pdb")
    """
    with open(output_pdb, "w") as f:
        f.write("REMARK  Generated from PRISM atoms\n")

        for i, atom in enumerate(atoms, 1):
            x, y, z = atom.coord
            # Match original PDB format: "ATOM      1  N   LIG L   1      ..."
            # Chain identifier is the first letter of residue name (not 'A')
            chain_id = residue_name[0] if residue_name else "A"
            line = f"ATOM  {i:5d}  {atom.name:<4s}{residue_name:>3s} {chain_id}   1    {x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00      {residue_name} \n"
            f.write(line)

        f.write("TER\n")
        f.write("END\n")


def read_hybrid_topology_dual(
    itp_file: str, gro_file: str, mol2_file: str = None, mol2_file_b: str = None
) -> Tuple[List[Atom], List[Atom], Dict[str, str]]:
    """
    Read hybrid topology file and return atoms for both states A and B.

    This function reads hybrid topology files (from FEbuilder or PRISM FEP)
    and returns separate atom lists for state A and state B, along with
    the correspondence mapping between them.

    Parameters
    ----------
    itp_file : str
        Path to hybrid ITP file
    gro_file : str
        Path to GRO file with coordinates
    mol2_file : str, optional
        Path to state A MOL2 file to determine atom order (for correct matching)
    mol2_file_b : str, optional
        Path to state B MOL2 file to avoid naming conflicts during renaming

    Returns
    -------
    Tuple[List[Atom], List[Atom], Dict[str, str]]
        (atoms_state_a, atoms_state_b, correspondence_map)
        correspondence_map maps state A atom names to state B atom names

    Notes
    -----
    ITP file format for hybrid topologies:
        nr type resnr residue atom cgnr charge mass typeB chargeB massB

    FEbuilder correspondence comments:
        ; name_b (state B): H06

    This function is useful for:
    - Testing hybrid topology generation
    - Visualizing dual-state mappings
    - Analyzing FEbuilder output
    """
    atoms_data = _parse_itp_atoms(itp_file, capture_state_b_names=True)
    correspondence_map = {atom["name"]: atom["name_b"] for atom in atoms_data if atom["name_b"]}
    original_names_by_id = {atom["id"]: atom["name"] for atom in atoms_data}

    atoms_data_a = _select_state_atoms(atoms_data, "a")
    atoms_data_b = _select_state_atoms(atoms_data, "b")

    coords_by_id, coords_by_name, _ = _load_structure_coordinates(gro_file)

    mol2_order, mol2_atom_names = _read_mol2_atom_names(mol2_file)
    _, mol2_atom_names_b = _read_mol2_atom_names(mol2_file_b)
    mol2_atom_names.update(mol2_atom_names_b)

    # Step 3: Create Atom objects for both states
    atoms_a = []
    atoms_b = []

    # Sort by MOL2 order if available, otherwise by original ID
    if mol2_order:
        # Create a mapping from atom name (without A/B suffix) to position in MOL2
        mol2_pos = {}
        for i, name in enumerate(mol2_order):
            mol2_pos[name] = i

        # Sort atoms by their position in MOL2 file
        def get_mol2_position(atom_name):
            # Remove A/B suffix
            name_clean = re.sub(r"([AB])(\d*)$", "", atom_name) if atom_name and atom_name[-1] in "AB" else atom_name
            return mol2_pos.get(name_clean, 999)  # Put unknown atoms at the end

        atoms_data_a.sort(key=lambda x: get_mol2_position(x["name"]))
        atoms_data_b.sort(key=lambda x: get_mol2_position(x["name"]))
    else:
        # Sort by original atom ID
        atoms_data_a.sort(key=lambda x: x["id"])
        atoms_data_b.sort(key=lambda x: x["id"])

    # Create state A atoms
    for atom_data in atoms_data_a:
        atom_name = atom_data["name"]
        atom_id = atom_data["id"]

        # Get coordinates: try name first, then ID
        coord = coords_by_name.get(atom_name, coords_by_id.get(atom_id, np.array([0.0, 0.0, 0.0])))

        atoms_a.append(
            Atom(
                name=atom_name,
                element=_extract_element(atom_name),
                coord=coord,
                charge=atom_data["charge"],
                atom_type=atom_data["type"],
                index=atom_data["id"],
            )
        )

    for atom_data in atoms_data_b:
        atom_name = atom_data["name"]
        atom_id = atom_data["id"]

        # Hybrid GRO files may still carry the original state-A atom name even
        # when the projected B-state name comes from FEbuilder comments.
        original_name = original_names_by_id.get(atom_id, atom_name)
        coord = coords_by_name.get(
            atom_name, coords_by_name.get(original_name, coords_by_id.get(atom_id, np.array([0.0, 0.0, 0.0])))
        )

        atoms_b.append(
            Atom(
                name=atom_name,
                element=_extract_element(atom_name),
                coord=coord,
                charge=atom_data["charge"],
                atom_type=atom_data["type"],
                index=atom_data["id"],
            )
        )

    return atoms_a, atoms_b, correspondence_map
