#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
GROMACS ITP File Builder

Generates GROMACS hybrid topology files with typeB/chargeB/massB encoding for
FEP calculations and can reconstruct full bonded sections from two source
ligand ITP files.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from ..core.hybrid_topology import HybridAtom


@dataclass
class HybridAtomRecord:
    """Parsed atom row from a hybrid ITP."""

    index: int
    name: str
    state_a_type: str
    state_a_charge: float
    mass: float
    state_b_type: Optional[str] = None
    state_b_charge: Optional[float] = None
    mass_b: Optional[float] = None
    name_b: Optional[str] = None  # B-side atom name for correct bonded mapping


@dataclass
class InteractionTerm:
    """Topology interaction term from a source ligand ITP."""

    atoms: Tuple[int, ...]
    funct: int
    params: List[str]


class ITPBuilder:
    """
    GROMACS ITP file generator for FEP calculations.

    Parameters
    ----------
    hybrid_atoms : List[HybridAtom]
        List of hybrid atoms with A/B state parameters.
    hybrid_params : Dict[str, List]
        Hybrid parameter dictionary. Recognized keys:
        - ``bonds``
        - ``pairs``
        - ``angles``
        - ``dihedrals``
        - ``impropers``
    """

    _SECTION_ATOM_COUNT = {
        "bonds": 2,
        "pairs": 2,
        "angles": 3,
        "dihedrals": 4,
        "impropers": 4,
    }

    def __init__(self, hybrid_atoms: List[HybridAtom], hybrid_params: Dict[str, List]):
        self.hybrid_atoms = hybrid_atoms
        self.hybrid_params = hybrid_params

    def write_itp(self, output_path: str, molecule_name: str = "HYB") -> None:
        """Write a hybrid topology ITP file."""
        with open(output_path, "w") as f:
            f.write("; GROMACS topology file for FEP calculation\n")
            f.write("; Generated by PRISM-FEP\n")
            f.write(";\n\n")

            # Write atomtypes section for dummy atoms
            atomtypes_section = self._get_atomtypes_section()
            if atomtypes_section:
                f.write(atomtypes_section)

            f.write("[ moleculetype ]\n")
            f.write("; Name            nrexcl\n")
            f.write(f"{molecule_name:16s}     3\n\n")

            f.write(self._get_atoms_section())

            if self.hybrid_params.get("bonds"):
                f.write(self._get_interaction_section("bonds", ";  ai    aj funct"))
            if self.hybrid_params.get("pairs"):
                f.write(self._get_interaction_section("pairs", ";  ai    aj funct"))
            if self.hybrid_params.get("angles"):
                f.write(self._get_interaction_section("angles", ";  ai    aj    ak funct"))
            if self.hybrid_params.get("dihedrals"):
                f.write(self._get_interaction_section("dihedrals", ";  ai    aj    ak    al funct"))
            if self.hybrid_params.get("impropers"):
                f.write(self._get_interaction_section("impropers", ";  ai    aj    ak    al funct"))

    def _get_atomtypes_section(self) -> str:
        """Generate the ``[ atomtypes ]`` section for dummy atoms."""
        dummy_types = {}
        for atom in self.hybrid_atoms:
            if atom.state_a_type.startswith("DUM_"):
                dummy_types[atom.state_a_type] = atom.mass
            if atom.state_b_type and atom.state_b_type.startswith("DUM_"):
                mass_b = atom.mass_b if atom.mass_b is not None else atom.mass
                dummy_types[atom.state_b_type] = mass_b

        if not dummy_types:
            return ""

        lines = [
            "[ atomtypes ]",
            "; name  at.num   mass     charge  ptype  sigma      epsilon",
        ]
        for dummy_type, mass in sorted(dummy_types.items()):
            lines.append(f"{dummy_type:6s}    0   {mass:8.5f}   0.000     A   0.0001     0.0000")
        lines.append("")
        return "\n".join(lines) + "\n"

    def _get_atoms_section(self) -> str:
        """Generate the ``[ atoms ]`` section."""
        lines = [
            "[ atoms ]",
            ";   nr       type  resnr residue  atom   cgnr     charge       mass  ",
            ";                                                                      typeB    chargeB      massB",
        ]

        for atom in self.hybrid_atoms:
            # CRITICAL: Add comment for B-side atom name BEFORE the atom line
            # This ensures _parse_hybrid_atom_records() can read the comment and
            # associate it with the correct atom
            if atom.name_b:
                lines.append(f"; name_b (state B): {atom.name_b}")

            line = f"{atom.index:6d} {atom.state_a_type:>10s}      1     LIG {atom.name:>5s}      1 "
            line += f"{atom.state_a_charge:10.6f} {atom.mass:10.5f}"

            if atom.state_b_type is not None and atom.state_b_charge is not None:
                if atom.state_b_type != atom.state_a_type or abs(atom.state_b_charge - atom.state_a_charge) > 1e-6:
                    line += f" {atom.state_b_type:>10s} {atom.state_b_charge:10.6f}"
                    mass_b = atom.mass_b if atom.mass_b is not None else atom.mass
                    line += f" {mass_b:10.5f}"

            lines.append(line)

        lines.append("")
        return "\n".join(lines) + "\n"

    def _get_interaction_section(self, section: str, header: str) -> str:
        """Generate a bonded interaction section."""
        section_name = "[ dihedrals ]" if section == "impropers" else f"[ {section} ]"
        lines = [section_name, header]

        for term in self.hybrid_params.get(section, []):
            atom_text = " ".join(f"{idx:6d}" for idx in term["atoms"])
            line = f"{atom_text} {term['funct']:6d}"
            params_a = term.get("params_a", [])
            params_b = term.get("params_b", [])
            if params_a:
                line += " " + " ".join(params_a)
            if params_b:
                line += " " + " ".join(params_b)
            lines.append(line)

        lines.append("")
        return "\n".join(lines) + "\n"

    @classmethod
    def build_hybrid_params_from_itps(
        cls,
        hybrid_itp: str,
        ligand_a_itp: str,
        ligand_b_itp: str,
    ) -> Dict[str, List]:
        """
        Reconstruct complete hybrid bonded terms from a hybrid atoms-only ITP and
        two source ligand ITP files.
        """
        hybrid_records = cls._parse_hybrid_atom_records(Path(hybrid_itp).read_text())
        name_map_a, name_map_b = cls._build_state_name_maps(hybrid_records)

        source_a = cls._parse_source_itp(Path(ligand_a_itp).read_text())
        source_b = cls._parse_source_itp(Path(ligand_b_itp).read_text())

        hybrid_params: Dict[str, List] = {key: [] for key in cls._SECTION_ATOM_COUNT}
        for section in cls._SECTION_ATOM_COUNT:
            hybrid_params[section] = cls._merge_section_terms(
                section=section,
                terms_a=source_a["sections"].get(section, []),
                terms_b=source_b["sections"].get(section, []),
                atom_names_a=source_a["atom_names"],
                atom_names_b=source_b["atom_names"],
                name_map_a=name_map_a,
                name_map_b=name_map_b,
            )
        return hybrid_params

    @classmethod
    def write_complete_hybrid_itp(
        cls,
        output_path: str,
        hybrid_itp: str,
        ligand_a_itp: str,
        ligand_b_itp: str,
        molecule_name: str = "HYB",
    ) -> Dict[str, List]:
        """
        Write a complete hybrid ITP using the atoms section from ``hybrid_itp``
        and bonded terms reconstructed from source ligand ITPs.
        """
        content = Path(hybrid_itp).read_text()
        hybrid_records = cls._parse_hybrid_atom_records(content)
        hybrid_atoms = [cls._record_to_hybrid_atom(record) for record in hybrid_records]
        hybrid_params = cls.build_hybrid_params_from_itps(hybrid_itp, ligand_a_itp, ligand_b_itp)
        cls(hybrid_atoms, hybrid_params).write_itp(output_path, molecule_name=molecule_name)
        return hybrid_params

    @staticmethod
    def _record_to_hybrid_atom(record: HybridAtomRecord) -> HybridAtom:
        return HybridAtom(
            name=record.name,
            name_b=record.name_b,
            index=record.index,
            state_a_type=record.state_a_type,
            state_a_charge=record.state_a_charge,
            state_b_type=record.state_b_type,
            state_b_charge=record.state_b_charge,
            mass=record.mass,
            mass_b=record.mass_b,
        )

    @classmethod
    def _parse_hybrid_atom_records(cls, content: str) -> List[HybridAtomRecord]:
        """Parse hybrid atom rows from an ITP content string."""
        records: List[HybridAtomRecord] = []
        in_atoms = False
        name_b_for_next_atom = None  # Store name_b from comment for next atom

        for line in content.splitlines():
            stripped = line.strip()
            if stripped.lower() == "[ atoms ]":
                in_atoms = True
                continue
            if stripped.startswith("[") and in_atoms:
                break

            # Parse name_b from comment (format: "; name_b (state B): XXXX")
            if in_atoms and stripped.startswith(";") and "name_b (state B):" in stripped:
                name_b_for_next_atom = stripped.split("name_b (state B):")[-1].strip()
                continue

            if not in_atoms or not stripped or stripped.startswith(";"):
                continue

            parts = stripped.split()
            if len(parts) < 8:
                continue

            state_b_type = None
            state_b_charge = None
            mass_b = None
            if len(parts) >= 10 and not cls._looks_like_float(parts[8]):
                state_b_type = parts[8]
                state_b_charge = float(parts[9])
                if len(parts) >= 11 and cls._looks_like_float(parts[10]):
                    mass_b = float(parts[10])
                else:
                    mass_b = float(parts[7])

            record = HybridAtomRecord(
                index=int(parts[0]),
                name=parts[4],
                state_a_type=parts[1],
                state_a_charge=float(parts[6]),
                mass=float(parts[7]),
                state_b_type=state_b_type,
                state_b_charge=state_b_charge,
                mass_b=mass_b,
                name_b=name_b_for_next_atom,  # Use name_b from comment if available
            )
            records.append(record)
            name_b_for_next_atom = None  # Reset for next atom

        return records

    @classmethod
    def _build_state_name_maps(cls, hybrid_records: List[HybridAtomRecord]) -> Tuple[Dict[str, int], Dict[str, int]]:
        """Build source atom-name to hybrid-index maps for states A and B."""
        map_a: Dict[str, int] = {}
        map_b: Dict[str, int] = {}

        for record in hybrid_records:
            state_a_dummy = record.state_a_type.startswith("DUM_")
            state_b_dummy = (record.state_b_type or "").startswith("DUM_")

            if record.name.endswith("A") and state_b_dummy and not state_a_dummy:
                map_a[record.name[:-1]] = record.index
                continue

            if record.name.endswith("B") and state_a_dummy and not state_b_dummy:
                map_b[record.name[:-1]] = record.index
                continue

            # Common atoms: use A-side name for map_a, B-side name for map_b
            # CRITICAL FIX: For common atoms with different names in A and B (e.g., H03 in A, H04 in B),
            # we must use the correct B-side atom name when building map_b to ensure bonded parameters
            # are correctly matched during the merging process.
            if not state_a_dummy:
                map_a[record.name] = record.index
            if not state_b_dummy:
                # Use B-side atom name if available, otherwise fall back to A-side name
                b_name = record.name_b if record.name_b else record.name
                map_b[b_name] = record.index

        return map_a, map_b

    @classmethod
    def _parse_source_itp(cls, content: str) -> Dict[str, Dict]:
        """Parse atoms and bonded sections from a source ligand ITP."""
        atom_names: Dict[int, str] = {}
        sections: Dict[str, List[InteractionTerm]] = {key: [] for key in cls._SECTION_ATOM_COUNT}

        current_section: Optional[str] = None
        for raw_line in content.splitlines():
            stripped = raw_line.strip()
            if not stripped:
                continue
            if stripped.startswith("#"):
                continue
            if stripped.startswith("["):
                lower = stripped.lower()
                if lower.startswith("[ atoms ]"):
                    current_section = "atoms"
                elif lower.startswith("[ bonds ]"):
                    current_section = "bonds"
                elif lower.startswith("[ pairs ]"):
                    current_section = "pairs"
                elif lower.startswith("[ angles ]"):
                    current_section = "angles"
                elif lower.startswith("[ dihedrals ]"):
                    current_section = "impropers" if "improper" in lower else "dihedrals"
                else:
                    current_section = None
                continue
            if stripped.startswith(";") or current_section is None:
                continue

            line = raw_line.split(";", 1)[0].strip()
            if not line:
                continue
            parts = line.split()

            if current_section == "atoms":
                if len(parts) >= 5:
                    atom_names[int(parts[0])] = parts[4]
                continue

            atom_count = cls._SECTION_ATOM_COUNT[current_section]
            if len(parts) < atom_count + 1:
                continue

            atom_indices = tuple(int(parts[i]) for i in range(atom_count))
            funct = int(parts[atom_count])
            params = parts[atom_count + 1 :]
            sections[current_section].append(InteractionTerm(atoms=atom_indices, funct=funct, params=params))

        return {"atom_names": atom_names, "sections": sections}

    @classmethod
    def _merge_section_terms(
        cls,
        section: str,
        terms_a: List[InteractionTerm],
        terms_b: List[InteractionTerm],
        atom_names_a: Dict[int, str],
        atom_names_b: Dict[int, str],
        name_map_a: Dict[str, int],
        name_map_b: Dict[str, int],
    ) -> List[Dict]:
        """Merge A/B section terms into hybrid interaction lines."""
        merged: Dict[Tuple, Dict[str, Optional[InteractionTerm]]] = {}

        def add_terms(
            state: str,
            terms: List[InteractionTerm],
            atom_names: Dict[int, str],
            name_map: Dict[str, int],
        ) -> None:
            for term in terms:
                hybrid_atoms = []
                for index in term.atoms:
                    atom_name = atom_names[index]
                    if atom_name not in name_map:
                        hybrid_atoms = []
                        break
                    hybrid_atoms.append(name_map[atom_name])
                if not hybrid_atoms:
                    continue

                canonical_atoms = cls._canonicalize_atoms(section, tuple(hybrid_atoms))
                key = (
                    canonical_atoms,
                    term.funct,
                    cls._parameter_signature(section, term.funct, term.params),
                )
                entry = merged.setdefault(key, {"A": None, "B": None})
                entry[state] = InteractionTerm(atoms=canonical_atoms, funct=term.funct, params=list(term.params))

        add_terms("A", terms_a, atom_names_a, name_map_a)
        add_terms("B", terms_b, atom_names_b, name_map_b)

        output: List[Dict] = []
        for key in sorted(merged, key=lambda item: item[0]):
            term_a = merged[key]["A"]
            term_b = merged[key]["B"]
            canonical_atoms, funct, _ = key

            if section == "pairs":
                output.append({"atoms": canonical_atoms, "funct": funct})
                continue

            if term_a is not None:
                params_a = list(term_a.params)
            else:
                params_a = cls._zeroize_params(section, funct, list(term_b.params))

            if term_b is not None:
                params_b = list(term_b.params)
            else:
                params_b = cls._zeroize_params(section, funct, list(term_a.params))

            output.append(
                {
                    "atoms": canonical_atoms,
                    "funct": funct,
                    "params_a": params_a,
                    "params_b": params_b,
                }
            )

        return output

    @staticmethod
    def _canonicalize_atoms(section: str, atoms: Tuple[int, ...]) -> Tuple[int, ...]:
        """Canonicalize interaction atom order for A/B matching."""
        if section in {"bonds", "pairs"}:
            return tuple(sorted(atoms))
        if section == "angles":
            return atoms if atoms[0] <= atoms[2] else atoms[::-1]
        return atoms if atoms <= atoms[::-1] else atoms[::-1]

    @staticmethod
    def _parameter_signature(section: str, funct: int, params: List[str]) -> Tuple[str, ...]:
        """
        Signature used to pair A/B terms whose non-perturbable identity must
        remain the same.
        """
        if section in {"dihedrals", "impropers"} and funct in {1, 4, 9} and len(params) >= 3:
            return (params[-1],)
        return tuple()

    @classmethod
    def _zeroize_params(cls, section: str, funct: int, params: List[str]) -> List[str]:
        """Generate a zero-force counterpart for terms missing in one state."""
        if not params:
            return []

        zero = list(params)

        if section in {"bonds", "angles"}:
            if len(zero) >= 2:
                # CRITICAL FIX: Use a small non-zero force constant instead of 0
                # to prevent atoms from flying apart during MD.
                # A force constant of 0 causes GROMACS to ignore the constraint entirely,
                # leading to energy explosions and LINCS failures.
                # Using 1.0 kJ/(mol·nm²) for bonds and 1.0 kJ/(mol·rad²) for angles
                # provides minimal restraint while allowing the interaction to disappear smoothly.
                zero[1] = "1.000000"  # Small non-zero force constant
            return zero

        if section in {"dihedrals", "impropers"}:
            if funct in {1, 4, 9} and len(zero) >= 3:
                zero[1] = "0.000000"
                return zero
            if funct == 3:
                return ["0.000000" for _ in zero]
            for i in range(len(zero)):
                if cls._looks_like_float(zero[i]):
                    zero[i] = "0.000000"
            return zero

        for i in range(len(zero)):
            if cls._looks_like_float(zero[i]):
                zero[i] = "0.000000"
        return zero

    @staticmethod
    def _looks_like_float(value: str) -> bool:
        try:
            float(value)
        except ValueError:
            return False
        return True
