#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
GROMACS ITP File Builder

Generates GROMACS ITP files with typeB/chargeB encoding for FEP calculations.
"""

from typing import List, Dict
from ..core.hybrid_topology import HybridAtom


class ITPBuilder:
    """
    GROMACS ITP file generator for FEP calculations

    Generates hybrid topology files with A/B state parameters encoded
    in typeB/chargeB columns following GROMACS FEP format.

    Parameters
    ----------
    hybrid_atoms : List[HybridAtom]
        List of hybrid atoms with A/B state parameters
    hybrid_params : Dict[str, List]
        Hybrid parameters dictionary containing:
        - 'bonds': List of bond parameters
        - 'angles': List of angle parameters
        - 'dihedrals': List of dihedral parameters
        - 'impropers': List of improper parameters

    Notes
    -----
    GROMACS FEP format requirements:
    - [ atoms ] section needs typeB/chargeB columns (massB for pmx)
    - Common atoms: type = typeB, charge = chargeB (write once)
    - Transformed atoms: typeA ≠ typeB (write both states)
    - Virtual atoms: use dummy types (DUM_*) from forcefield
    """

    def __init__(self, hybrid_atoms: List[HybridAtom], hybrid_params: Dict[str, List]):
        self.hybrid_atoms = hybrid_atoms
        self.hybrid_params = hybrid_params

    def write_itp(self, output_path: str, molecule_name: str = "HYB"):
        """
        Write hybrid topology to GROMACS ITP file

        File structure:
        1. Header comments
        2. [ moleculetype ]
        3. [ atoms ] (with typeB/chargeB columns)
        4. [ bonds ]
        5. [ pairs ]
        6. [ angles ]
        7. [ dihedrals ]
        8. [ impropers ]

        Parameters
        ----------
        output_path : str
            Path to output ITP file
        molecule_name : str, optional
            Molecule name (default: "HYB")
        """
        with open(output_path, "w") as f:
            # Header
            f.write("; GROMACS topology file for FEP calculation\n")
            f.write("; Generated by PRISM-FEP\n")
            f.write(";\n\n")

            # Moleculetype
            f.write("[ moleculetype ]\n")
            f.write("; Name            nrexcl\n")
            f.write(f"{molecule_name:16s}     3\n\n")

            # Atoms section
            f.write(self._get_atoms_section())

            # TODO: Bonds, angles, dihedrals sections
            # These require parameter mapping from original ligands
            if self.hybrid_params.get("bonds"):
                f.write(self._get_bonds_section())
            if self.hybrid_params.get("angles"):
                f.write(self._get_angles_section())
            if self.hybrid_params.get("dihedrals"):
                f.write(self._get_dihedrals_section())
            if self.hybrid_params.get("impropers"):
                f.write(self._get_impropers_section())

    def _get_atoms_section(self) -> str:
        """
        Generate [ atoms ] section with typeB/chargeB columns

        This is the most critical section for GROMACS FEP format.

        Returns
        -------
        str
            Formatted [ atoms ] section

        Notes
        -----
        GROMACS format (important):
        ;   nr       type  resnr residue  atom   cgnr    charge   mass    typeB   chargeB   massB
        Common atoms: only write first 8 columns (typeA = typeB, chargeA = chargeB)
        Transformed atoms: write all columns (typeA ≠ typeB)
        Surrounding atoms: only write first 8 columns (no typeB/chargeB)
        """
        lines = []
        lines.append("[ atoms ]")
        lines.append(";   nr       type  resnr residue  atom   cgnr     charge       mass  ")
        lines.append(
            ";                                                                      typeB    chargeB      massB"
        )

        for atom in self.hybrid_atoms:
            # Basic columns (always present)
            line = f"{atom.index:6d} {atom.state_a_type:>10s}      1     LIG {atom.name:>5s}      1 "
            line += f"{atom.state_a_charge:10.6f} {atom.mass:10.5f}"

            # Add typeB/chargeB/massB for dual-topology atoms
            if atom.state_b_type is not None and atom.state_b_charge is not None:
                # Only add typeB/chargeB if they differ from typeA/chargeA
                if atom.state_b_type != atom.state_a_type or abs(atom.state_b_charge - atom.state_a_charge) > 1e-6:
                    line += f" {atom.state_b_type:>10s} {atom.state_b_charge:10.6f}"

                    # Add massB if different from mass
                    if atom.mass_b is not None and abs(atom.mass_b - atom.mass) > 1e-6:
                        line += f" {atom.mass_b:10.5f}"

            lines.append(line)

        lines.append("")  # Empty line after section
        return "\n".join(lines) + "\n"

    def _get_bonds_section(self) -> str:
        """Generate [ bonds ] section"""
        lines = []
        lines.append("[ bonds ]")
        lines.append(";  ai    aj funct            c0            c1            c2            c3")
        # TODO: Implement bond parameter mapping
        lines.append("")
        return "\n".join(lines) + "\n"

    def _get_angles_section(self) -> str:
        """Generate [ angles ] section"""
        lines = []
        lines.append("[ angles ]")
        lines.append(";  ai    aj    ak funct            c0            c1            c2            c3")
        # TODO: Implement angle parameter mapping
        lines.append("")
        return "\n".join(lines) + "\n"

    def _get_dihedrals_section(self) -> str:
        """Generate [ dihedrals ] section"""
        lines = []
        lines.append("[ dihedrals ]")
        lines.append(
            ";  ai    aj    ak    al funct            c0            c1            c2            c3            c4            c5"
        )
        # TODO: Implement dihedral parameter mapping
        lines.append("")
        return "\n".join(lines) + "\n"

    def _get_impropers_section(self) -> str:
        """Generate [ impropers ] section"""
        lines = []
        lines.append("[ dihedrals ]")
        lines.append(";  ai    aj    ak    al funct            c0            c1            c2            c3")
        # TODO: Implement improper parameter mapping
        lines.append("")
        return "\n".join(lines) + "\n"
