#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
GROMACS MDP Templates for FEP Calculations

Provides MDP file templates and generation functions for FEP simulations.
"""

from typing import Dict

FEP_PROD_MDP = """
; FEP Production MDP - Generated by PRISM-FEP
; Date: {date}
;
; This MDP file is configured for alchemical free energy perturbation
; calculations using GROMACS coupled-topology formalism.
;

include = -I. -I../mdps -I../hybrid

; Integrator
integrator  = md
dt          = 0.002
nsteps      = 500000

; Output
nstxout     = 5000
nstvout     = 5000
nstenergy   = 1000
nstlog      = 1000

; Free energy parameters
free-energy              = yes
init-lambda              = 0
delta-lambda             = 0
calc-lambda-neighbors    = 4

; Lambda vector
lambda-points            = {lambda_points}
fep-lambdas              = {fep_lambdas}

; Coulomb and VDW lambdas (separated for better sampling)
coul-lambdas             = {coul_lambdas}
vdw-lambdas              = {vdw_lambdas}

; Soft-core parameters (avoid singularities)
sc-alpha                 = 0.5
sc-power                 = 1
sc-sigma                 = 0.3

; Coupled perturbations
couple-moltype           = HYB
couple-lambda0           = vdw-q
couple-lambda1           = vdw-q
couple-intramol          = yes

; Nonbonded settings
cutoff-scheme   = Verlet
ns_type         = grid
nstlist         = 10
rcoulomb        = 1.0
rvdw            = 1.0

; Temperature coupling
tcoupl          = V-rescale
tc-grps         = Protein_LIG HYB Water_and_ions
tau-t           = 0.5     0.5     0.5
ref-t           = 300     300     300

; Pressure coupling
pcoupl          = Parrinello-Rahman
pcoupltype      = isotropic
tau-p           = 2.0
ref-p           = 1.0
compressibility = 4.5e-5

; Electrostatics
coulombtype     = PME
rcoulomb        = 1.0

; Van der Waals
vdwtype         = Cut-off
DispCorr        = EnerPres

; Energy groups
energygrp-table = Protein_LIG HYB
"""


def write_fep_mdps(
    output_dir: str, lambda_points: int = 11, soft_core_alpha: float = 0.5, soft_core_sigma: float = 0.3
):
    """
    Write FEP MDP files for all lambda windows

    Parameters
    ----------
    output_dir : str
        Output directory for MDP files
    lambda_points : int, optional
        Number of lambda windows (default: 11)
    soft_core_alpha : float, optional
        Soft-core alpha parameter (default: 0.5)
    soft_core_sigma : float, optional
        Soft-core sigma parameter (default: 0.3)

    Raises
    ------
    NotImplementedError
        To be implemented in next phase
    """
    raise NotImplementedError("FEP MDP file generation to be implemented")


def _generate_lambda_schedule(lambda_points: int = 11) -> Dict[str, str]:
    """
    Generate lambda schedule for FEP calculations

    Parameters
    ----------
    lambda_points : int, optional
        Number of lambda windows (default: 11)

    Returns
    -------
    Dict[str, str]
        Dictionary containing formatted lambda strings
    """
    import numpy as np

    # Linear lambdas
    lambdas = np.linspace(0.0, 1.0, lambda_points)

    # Coulomb lambdas (linear)
    coul_lambdas_str = " ".join([f"{x:.1f}" for x in lambdas])

    # VDW lambdas (nonlinear to avoid singularities at endpoints)
    # More points at endpoints with soft-core
    if lambda_points == 11:
        vdw_lambdas = [0.0, 0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 1.0, 1.0]
    else:
        # Generic schedule - asymmetric around 0.5
        vdw_lambdas = list(lambdas)
        vdw_lambdas = vdw_lambdas[: lambda_points // 2] + vdw_lambdas[lambda_points // 2 :]

    vdw_lambdas_str = " ".join([f"{x:.2f}" for x in vdw_lambdas])

    fep_lambdas_str = coul_lambdas_str  # For now, same as coulomb

    return {
        "fep_lambdas": fep_lambdas_str,
        "coul_lambdas": coul_lambdas_str,
        "vdw_lambdas": vdw_lambdas_str,
    }
