#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""GROMACS MDP helpers for PRISM-FEP."""

import json
from pathlib import Path
from typing import Dict, Optional, List

FEP_PROD_MDP = """
; FEP Production MDP - Generated by PRISM-FEP
; Date: {date}
;
; This MDP file is configured for alchemical free energy perturbation
; calculations using GROMACS coupled-topology formalism.
;

include = -I. -I../mdps -I../hybrid

; Integrator
integrator  = md
dt          = {dt}
nsteps      = {nsteps}

; Output
nstxout     = 5000
nstvout     = 5000
nstenergy   = {nstenergy}
nstlog      = {nstlog}
nstxout-compressed = {nstxout_compressed}

; Free energy parameters
free-energy              = yes
init-lambda-state        = {init_lambda_state}
delta-lambda             = 0
calc-lambda-neighbors    = 1
nstdhdl                  = 100
separate-dhdl-file       = yes

; Lambda schedules (strategy: {strategy})
coul-lambdas             = {coul_lambdas}
vdw-lambdas              = {vdw_lambdas}
bonded-lambdas           = {bonded_lambdas}
mass-lambdas             = {mass_lambdas}

; Soft-core parameters (avoid singularities)
sc-alpha                 = {sc_alpha}
sc-power                 = 1
sc-sigma                 = {sc_sigma}
sc-coul                  = yes

; NOTE: couple-moltype is NOT used because the hybrid topology
; already defines typeB/chargeB in the ITP file

; Nonbonded settings
cutoff-scheme   = Verlet
ns_type         = grid
nstlist         = 200  ; Optimized for multi-GPU with PME (matching bound performance)
rcoulomb        = {rcoulomb}
rvdw            = {rvdw}
table-extension = 2.0

; For dual-topology FEP, state A and state B atoms can have large separations.
; The table extension ensures the lookup table covers these long-range interactions.

; Temperature coupling
tcoupl          = {tcoupl}
tc-grps         = System
tau-t           = {tau_t}
ref-t           = {temp}

; Pressure coupling
pcoupl          = {pcoupl}
pcoupltype      = {pcoupltype}
tau-p           = {tau_p}
ref-p           = {pressure}
compressibility = {compressibility}

; Electrostatics
coulombtype     = {coulombtype}
pme_order       = {pme_order}
fourierspacing  = {fourierspacing}

; Van der Waals
vdwtype         = Cut-off
DispCorr        = EnerPres

; Periodic boundary conditions
pbc             = xyz

; Constraints
; For hybrid topologies, use standard constraints with increased LINCS accuracy
constraints             = {constraints_type}
constraint-algorithm    = {constraints_algorithm}
lincs-order             = 6
lincs-iter              = 2
lincs-warnangle         = 30
"""


def write_fep_mdps(
    output_dir: str,
    lambda_strategy: str = "decoupled",
    lambda_distribution: str = "nonlinear",
    lambda_windows: int = 32,
    coul_windows: int = 12,
    vdw_windows: int = 20,
    custom_coul_lambdas: Optional[List[float]] = None,
    custom_vdw_lambdas: Optional[List[float]] = None,
    soft_core_alpha: float = 0.5,
    soft_core_sigma: float = 0.3,
    config: Optional[Dict] = None,
    leg_name: str = "fep",
):
    """
    Write FEP MDP files for all lambda windows

    Parameters
    ----------
    output_dir : str
        Output directory for MDP files
    lambda_strategy : str, optional
        Lambda strategy: 'coupled', 'decoupled', or 'custom' (default: 'decoupled')
    lambda_distribution : str, optional
        Distribution type: 'linear', 'nonlinear', or 'quadratic' (default: 'nonlinear')
    lambda_windows : int, optional
        Total number of lambda windows for coupled mode (default: 32)
    coul_windows : int, optional
        Number of windows for electrostatics stage in decoupled mode (default: 12)
    vdw_windows : int, optional
        Number of windows for VDW stage in decoupled mode (default: 20)
    custom_coul_lambdas : List[float], optional
        Custom coulomb lambda array for custom strategy
    custom_vdw_lambdas : List[float], optional
        Custom VDW lambda array for custom strategy
    soft_core_alpha : float, optional
        Soft-core alpha parameter (default: 0.5)
    soft_core_sigma : float, optional
        Soft-core sigma parameter (default: 0.3)
    config : dict, optional
        Configuration dictionary with simulation parameters
    leg_name : str, optional
        Name of the FEP leg (default: "fep")
    """
    from prism.utils.config import ConfigurationManager

    config = config or {}
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Load PRISM default configuration for MDP settings
    config_manager = ConfigurationManager()
    prism_config = config_manager.config

    # Get simulation parameters (use FEP config if provided, otherwise PRISM defaults)
    sim_cfg = config.get("simulation", {})
    fep_cfg = config.get("fep", {})

    # Temperature and pressure
    temp = sim_cfg.get("temperature", prism_config.get("md", {}).get("temperature", 310))
    pressure = sim_cfg.get("pressure", prism_config.get("md", {}).get("pressure", 1.0))
    dt = sim_cfg.get("dt", prism_config.get("md", {}).get("dt", 0.002))

    # Equilibration times
    nvt_ps = sim_cfg.get("equilibration_nvt_time_ps", 500)
    npt_ps = sim_cfg.get("equilibration_npt_time_ps", 500)
    npt_short_ps = sim_cfg.get("per_window_npt_time_ps", fep_cfg.get("per_window_npt_time_ps", 100))

    # Production time - check both fep and simulation sections
    prod_ns = fep_cfg.get("production_time_ns", sim_cfg.get("production_time_ns", 5))

    # Get electrostatics and VDW parameters from PRISM config
    elec_cfg = prism_config.get("electrostatics", {})
    vdw_cfg = prism_config.get("vdw", {})
    rcoulomb = config.get("electrostatics", {}).get("rcoulomb", elec_cfg.get("rcoulomb", 1.0))
    rvdw = config.get("vdw", {}).get("rvdw", vdw_cfg.get("rvdw", 1.0))
    coulombtype = elec_cfg.get("coulombtype", "PME")
    pme_order = elec_cfg.get("pme_order", 4)
    fourierspacing = elec_cfg.get("fourierspacing", 0.16)

    # Get output parameters
    output_cfg = config.get("output", {})
    traj_interval = int(output_cfg.get("trajectory_interval_ps", 500) / dt)
    energy_interval = int(output_cfg.get("energy_interval_ps", 10) / dt)
    log_interval = int(output_cfg.get("log_interval_ps", 10) / dt)

    # Get constraints from PRISM config
    constraints_cfg = prism_config.get("constraints", {})
    constraints_type = constraints_cfg.get("type", "h-bonds")
    constraints_algorithm = constraints_cfg.get("algorithm", "lincs")

    schedule = _generate_lambda_schedule(
        strategy=lambda_strategy,
        distribution=lambda_distribution,
        total_windows=lambda_windows,
        coul_windows=coul_windows,
        vdw_windows=vdw_windows,
        custom_coul=custom_coul_lambdas,
        custom_vdw=custom_vdw_lambdas,
    )
    schedule["soft_core_alpha"] = soft_core_alpha
    schedule["soft_core_sigma"] = soft_core_sigma
    (output_path / "lambda_schedule.json").write_text(json.dumps(schedule, indent=2) + "\n")

    # Generate EM MDP (same as PRISM standard)
    # Support both "energy_minimization" and "simulation" config keys
    em_config = prism_config.get("energy_minimization", prism_config.get("simulation", {}))
    em_mdp = f"""; {leg_name} EM - Energy Minimization
integrator      = {em_config.get('integrator', 'steep')}
emtol           = {em_config.get('emtol', 1000.0)}
emstep          = {em_config.get('emstep', 0.01)}
nsteps          = 100000

; Output control
nstxout         = 500
nstvout         = 500
nstenergy       = 500
nstlog          = 500

; Neighbor searching
cutoff-scheme   = Verlet
ns_type         = grid
nstlist         = 10
rcoulomb        = {rcoulomb}
rvdw            = {rvdw}
table-extension = 2.0

; For dual-topology FEP, state A and state B atoms can have large separations.
; The table extension ensures the lookup table covers these long-range interactions.

; Electrostatics
coulombtype     = {coulombtype}
pme_order       = {pme_order}
fourierspacing  = {fourierspacing}

; VDW
vdwtype         = Cut-off
DispCorr        = EnerPres

; Temperature and pressure coupling are off during EM
tcoupl          = no
pcoupl          = no

; Periodic boundary conditions
pbc             = xyz

; Constraints
; For FEP hybrid topologies, constraints are disabled during EM because
; overlapping dual-topology atoms (state A and state B) cause LINCS failures.
; Energy minimization with bonded parameters will resolve the geometry.
constraints             = none
"""
    (output_path / "em.mdp").write_text(em_mdp)

    # Generate NVT MDP (same as PRISM standard)
    nvt_config = prism_config.get("nvt", {})
    nvt_mdp = f"""; {leg_name} NVT - NVT Equilibration
define              = -DPOSRES
integrator          = md
dt                  = {dt}
nsteps              = {int(nvt_ps / dt)}

; Output control
nstxout             = 0
nstvout             = 0
nstfout             = 0
nstlog              = {log_interval}
nstenergy           = {energy_interval}
nstxout-compressed  = 0

; Neighbor searching
cutoff-scheme       = Verlet
ns_type             = grid
nstlist             = 80  ; Increased from 10 for better GPU efficiency (reduces CPU-GPU sync)
rcoulomb            = {rcoulomb}
rvdw                = {rvdw}
table-extension     = 2.0

; For dual-topology FEP, state A and state B atoms can have large separations.
; The table extension ensures the lookup table covers these long-range interactions.

; Electrostatics
coulombtype         = {coulombtype}
pme_order           = {pme_order}
fourierspacing      = {fourierspacing}

; VDW
vdwtype             = Cut-off
DispCorr            = EnerPres

; Temperature coupling
tcoupl              = {nvt_config.get('tcoupl', 'V-rescale')}
tc-grps             = System
tau_t               = {nvt_config.get('tau_t', 0.1)}
ref_t               = {temp}

; Pressure coupling is off during NVT
pcoupl              = no

; Periodic boundary conditions
pbc                 = xyz

; Velocity generation
gen_vel             = yes
gen_temp            = {temp}
gen_seed            = -1

; Constraints
; For hybrid topologies, use standard constraints with increased LINCS accuracy
constraints             = {constraints_type}
constraint-algorithm    = {constraints_algorithm}
lincs-order             = 6
lincs-iter              = 2
lincs-warnangle         = 30
"""
    (output_path / "nvt.mdp").write_text(nvt_mdp)

    # Generate NPT MDP (same as PRISM standard)
    npt_config = prism_config.get("npt", {})
    npt_mdp = f"""; {leg_name} NPT - NPT Equilibration
define              = -DPOSRES
integrator          = md
dt                  = {dt}
nsteps              = {int(npt_ps / dt)}

; Output control
nstxout             = 0
nstvout             = 0
nstfout             = 0
nstlog              = {log_interval}
nstenergy           = {energy_interval}
nstxout-compressed  = 0

; Neighbor searching
cutoff-scheme       = Verlet
ns_type             = grid
nstlist             = 80  ; Increased from 10 for better GPU efficiency (reduces CPU-GPU sync)
rcoulomb            = {rcoulomb}
rvdw                = {rvdw}
table-extension     = 2.0

; For dual-topology FEP, state A and state B atoms can have large separations.
; The table extension ensures the lookup table covers these long-range interactions.

; Electrostatics
coulombtype         = {coulombtype}
pme_order           = {pme_order}
fourierspacing      = {fourierspacing}

; VDW
vdwtype             = Cut-off
DispCorr            = EnerPres

; Temperature coupling
tcoupl              = {npt_config.get('tcoupl', 'V-rescale')}
tc-grps             = System
tau_t               = {npt_config.get('tau_t', 0.1)}
ref_t               = {temp}

; Pressure coupling
pcoupl              = {npt_config.get('pcoupl', 'C-rescale')}
pcoupltype          = {npt_config.get('pcoupltype', 'isotropic')}
tau_p               = {npt_config.get('tau_p', 2.0)}
ref_p               = {pressure}
compressibility     = {npt_config.get('compressibility', 4.5e-5)}

; Periodic boundary conditions
pbc                 = xyz

; Velocity generation
gen_vel             = no

; Constraints
; For hybrid topologies, use standard constraints with increased LINCS accuracy
constraints             = {constraints_type}
constraint-algorithm    = {constraints_algorithm}
lincs-order             = 6
lincs-iter              = 2
lincs-warnangle         = 30
"""
    (output_path / "npt.mdp").write_text(npt_mdp)

    # NOTE: NPT short MDPs are now generated per-window below (after lambda schedule is defined)
    # to include lambda-specific parameters for each window

    lambda_values = schedule["fep_lambdas"].split()
    prod_steps = int(prod_ns * 1000 / dt)

    # Get common MD parameters from PRISM config
    md_config = prism_config.get("md", {})
    tcoupl = md_config.get("tcoupl", "V-rescale")
    tau_t = md_config.get("tau_t", 0.5)
    pcoupl = md_config.get("pcoupl", "Parrinello-Rahman")
    pcoupltype = md_config.get("pcoupltype", "isotropic")
    tau_p = md_config.get("tau_p", 2.0)
    compressibility = md_config.get("compressibility", 4.5e-5)

    # Generate per-window NPT short MDPs with lambda-specific parameters
    for index, lambda_value in enumerate(lambda_values):
        npt_short_mdp = f"""; {leg_name} NPT Short - Per-Window NPT Equilibration (Window {index:02d})
define              = -DPOSRES
integrator          = md
dt                  = 0.001  ; Reduced timestep for stability at intermediate lambda states
nsteps              = {int(npt_short_ps / 0.001)}

; Output control
nstxout             = 0
nstvout             = 0
nstfout             = 0
nstlog              = {log_interval}
nstenergy           = {energy_interval}
nstxout-compressed  = 0

; Free energy parameters
free-energy              = yes
init-lambda-state        = {index}
delta-lambda             = 0
calc-lambda-neighbors    = -1
nstdhdl                  = 100
separate-dhdl-file       = yes

; Lambda schedules (strategy: {schedule['strategy']})
coul-lambdas             = {schedule['coul_lambdas']}
vdw-lambdas              = {schedule['vdw_lambdas']}
bonded-lambdas           = {schedule['bonded_lambdas']}
mass-lambdas             = {schedule['mass_lambdas']}

; Soft-core parameters (avoid singularities)
; Increased sc-sigma for smoother VDW transformation and reduced clashes at intermediate lambda
sc-alpha                 = 0.5
sc-power                 = 1
sc-sigma                 = 0.5
sc-coul                  = yes

; NOTE: couple-moltype is NOT used because the hybrid topology
; already defines typeB/chargeB in the ITP file

; Neighbor searching
cutoff-scheme       = Verlet
ns_type             = grid
nstlist             = 80  ; Increased from 10 for better GPU efficiency (reduces CPU-GPU sync)
rcoulomb            = {rcoulomb}
rvdw                = {rvdw}
table-extension     = 2.0

; For dual-topology FEP, state A and state B atoms can have large separations.
; The table extension ensures the lookup table covers these long-range interactions.

; Electrostatics
coulombtype         = {coulombtype}
pme_order           = {pme_order}
fourierspacing      = {fourierspacing}

; VDW
vdwtype             = Cut-off
DispCorr            = EnerPres

; Temperature coupling
tcoupl              = {tcoupl}
tc-grps             = System
tau_t               = {tau_t}
ref_t               = {temp}

; Pressure coupling
; Use C-rescale for stability during per-window NPT short at intermediate lambda states
pcoupl              = C-rescale
pcoupltype          = isotropic
tau_p               = 1.0
ref_p               = {pressure}
compressibility     = {compressibility}

; Periodic boundary conditions
pbc                 = xyz

; Velocity generation
gen_vel             = no

; Constraints
; For hybrid topologies, use standard constraints with increased LINCS accuracy
constraints             = {constraints_type}
constraint-algorithm    = {constraints_algorithm}
lincs-order             = 6
lincs-iter              = 2
lincs-warnangle         = 30

; Lambda window {index}: nominal lambda = {lambda_value}
"""
        (output_path / f"npt_short_{index:02d}.mdp").write_text(npt_short_mdp)

    # Generate production MDPs for each lambda window
    for index, lambda_value in enumerate(lambda_values):
        prod_mdp = FEP_PROD_MDP.format(
            date="generated",
            dt=dt,
            nsteps=prod_steps,
            nstenergy=energy_interval,
            nstlog=log_interval,
            nstxout_compressed=traj_interval,
            init_lambda_state=index,
            strategy=schedule["strategy"],
            coul_lambdas=schedule["coul_lambdas"],
            vdw_lambdas=schedule["vdw_lambdas"],
            bonded_lambdas=schedule["bonded_lambdas"],
            mass_lambdas=schedule["mass_lambdas"],
            sc_alpha=soft_core_alpha,
            sc_sigma=soft_core_sigma,
            rcoulomb=rcoulomb,
            rvdw=rvdw,
            coulombtype=coulombtype,
            pme_order=pme_order,
            fourierspacing=fourierspacing,
            tcoupl=tcoupl,
            tau_t=tau_t,
            temp=temp,
            pcoupl=pcoupl,
            pcoupltype=pcoupltype,
            tau_p=tau_p,
            pressure=pressure,
            compressibility=compressibility,
            constraints_type=constraints_type,
            constraints_algorithm=constraints_algorithm,
        )
        prod_mdp += f"\n; Lambda window {index}: nominal lambda = {lambda_value}\n"
        (output_path / f"prod_{index:02d}.mdp").write_text(prod_mdp)


def _generate_distribution(n_points: int, dist_type: str) -> List[float]:
    """
    Generate lambda distribution

    Parameters
    ----------
    n_points : int
        Number of lambda points
    dist_type : str
        Distribution type: 'linear', 'nonlinear', or 'quadratic'

    Returns
    -------
    List[float]
        Lambda values from 0.0 to 1.0
    """
    import numpy as np

    if dist_type == "linear":
        return list(np.linspace(0.0, 1.0, n_points))

    elif dist_type == "nonlinear":
        # Reference distribution from tests/gxf/FEP/ref/gxf_gmx_mdp_re/prod.mdp (32 points)
        # Dense at endpoints to capture steep free energy changes
        ref_32 = [
            0.00,
            0.01,
            0.02,
            0.04,
            0.06,
            0.09,
            0.12,
            0.16,
            0.20,
            0.24,
            0.28,
            0.32,
            0.36,
            0.40,
            0.44,
            0.48,
            0.52,
            0.56,
            0.60,
            0.64,
            0.68,
            0.72,
            0.76,
            0.80,
            0.84,
            0.88,
            0.91,
            0.94,
            0.96,
            0.98,
            0.99,
            1.00,
        ]

        if n_points == 32:
            return ref_32
        elif n_points < 32:
            # Subsample from ref_32
            indices = np.linspace(0, 31, n_points, dtype=int)
            return [ref_32[i] for i in indices]
        else:
            # Interpolate to more points
            x_ref = np.linspace(0, 1, 32)
            x_new = np.linspace(0, 1, n_points)
            return list(np.interp(x_new, x_ref, ref_32))

    elif dist_type == "quadratic":
        # Quadratic distribution: denser at endpoints
        x = np.linspace(0, 1, n_points)
        # Use x^2 for first half, 1-(1-x)^2 for second half
        lambdas = []
        for i, val in enumerate(x):
            if val <= 0.5:
                lambdas.append(2 * val**2)
            else:
                lambdas.append(1 - 2 * (1 - val) ** 2)
        return lambdas

    else:
        raise ValueError(f"Unknown distribution type: {dist_type}")


def _generate_lambda_schedule(
    strategy: str = "decoupled",
    distribution: str = "nonlinear",
    total_windows: int = 32,
    coul_windows: int = 12,
    vdw_windows: int = 20,
    custom_coul: Optional[List[float]] = None,
    custom_vdw: Optional[List[float]] = None,
) -> Dict[str, str]:
    """
    Generate lambda schedule for FEP calculations

    Parameters
    ----------
    strategy : str, optional
        Lambda strategy: 'coupled', 'decoupled', or 'custom' (default: 'decoupled')
    distribution : str, optional
        Distribution type: 'linear', 'nonlinear', or 'quadratic' (default: 'nonlinear')
    total_windows : int, optional
        Total number of lambda windows for coupled mode (default: 32)
    coul_windows : int, optional
        Number of windows for electrostatics stage in decoupled mode (default: 12)
    vdw_windows : int, optional
        Number of windows for VDW stage in decoupled mode (default: 20)
    custom_coul : List[float], optional
        Custom coulomb lambda array
    custom_vdw : List[float], optional
        Custom VDW lambda array

    Returns
    -------
    Dict[str, str]
        Dictionary containing formatted lambda strings:
        - fep_lambdas: Main lambda schedule
        - coul_lambdas: Coulomb lambda schedule
        - vdw_lambdas: VDW lambda schedule
        - bonded_lambdas: Bonded interactions lambda schedule
        - mass_lambdas: Mass lambda schedule
        - strategy: Strategy used
        - n_windows: Total number of windows
    """
    if strategy == "custom":
        # Use custom lambda arrays
        if custom_coul is None or custom_vdw is None:
            raise ValueError("custom strategy requires both custom_coul and custom_vdw")

        coul_lambdas = custom_coul
        vdw_lambdas = custom_vdw
        n_windows = max(len(coul_lambdas), len(vdw_lambdas))

        # Pad shorter array with final value
        if len(coul_lambdas) < n_windows:
            coul_lambdas = list(coul_lambdas) + [coul_lambdas[-1]] * (n_windows - len(coul_lambdas))
        if len(vdw_lambdas) < n_windows:
            vdw_lambdas = list(vdw_lambdas) + [vdw_lambdas[-1]] * (n_windows - len(vdw_lambdas))

    elif strategy == "coupled":
        # All lambdas change together from 0 to 1
        lambdas = _generate_distribution(total_windows, distribution)
        coul_lambdas = lambdas
        vdw_lambdas = lambdas
        n_windows = total_windows

    elif strategy == "decoupled":
        # Stage 1: Turn off electrostatics (coul 0→1, vdw=0)
        # Stage 2: Turn off VDW (coul=1, vdw 0→1)
        coul_stage = _generate_distribution(coul_windows, distribution)
        vdw_stage = _generate_distribution(vdw_windows, distribution)

        # Stage 1: coul changes, vdw stays at 0
        coul_lambdas = coul_stage + [1.0] * vdw_windows
        vdw_lambdas = [0.0] * coul_windows + vdw_stage

        n_windows = coul_windows + vdw_windows

    else:
        raise ValueError(f"Unknown strategy: {strategy}. Use 'coupled', 'decoupled', or 'custom'")

    # Bonded and mass lambdas follow the same schedule as coul (can be customized)
    bonded_lambdas = coul_lambdas
    mass_lambdas = coul_lambdas

    # Format as strings
    coul_lambdas_str = " ".join([f"{x:.2f}" for x in coul_lambdas])
    vdw_lambdas_str = " ".join([f"{x:.2f}" for x in vdw_lambdas])
    bonded_lambdas_str = " ".join([f"{x:.2f}" for x in bonded_lambdas])
    mass_lambdas_str = " ".join([f"{x:.2f}" for x in mass_lambdas])
    fep_lambdas_str = coul_lambdas_str  # Main lambda schedule

    return {
        "fep_lambdas": fep_lambdas_str,
        "coul_lambdas": coul_lambdas_str,
        "vdw_lambdas": vdw_lambdas_str,
        "bonded_lambdas": bonded_lambdas_str,
        "mass_lambdas": mass_lambdas_str,
        "strategy": strategy,
        "n_windows": n_windows,
    }
