#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Membrane-specific GROMACS MDP generation.

Membrane simulations differ from soluble-protein runs in three crucial ways:

* **Semiisotropic pressure coupling** — the membrane plane (xy) and normal (z)
  are coupled separately so the bilayer can relax its area-per-lipid without the
  box collapsing. Isotropic coupling keeps the membrane under artificial tension.
* **Grouped thermostatting** — solute, membrane and solvent are coupled to
  separate v-rescale baths (never split ions from their solvent).
* **van-der-Waals treatment** — CHARMM36 lipids *require* a force-switch
  modifier (potential-based switching produces a spurious gel phase and a wrong
  area-per-lipid); AMBER/Lipid21 use a plain cutoff with dispersion correction.

This module writes a four-stage membrane protocol (EM -> NVT -> NPT -> MD). The
thermostat groups default to ``SOLU`` / ``MEMB`` / ``SOLV`` (an index file with
those groups is generated by the membrane builder).
"""

from __future__ import annotations

import os
from typing import Sequence


def _vdw_block(ff_family: str) -> str:
    """Return the vdW/electrostatics block appropriate for the lipid FF."""
    if ff_family == "charmm":
        # CHARMM36 lipids: force-switch is mandatory.
        return (
            "cutoff-scheme           = Verlet\n"
            "coulombtype             = PME\n"
            "rcoulomb                = 1.2\n"
            "vdwtype                 = Cut-off\n"
            "vdw-modifier            = Force-switch\n"
            "rvdw-switch             = 1.0\n"
            "rvdw                    = 1.2\n"
            "rlist                   = 1.2\n"
            "DispCorr                = no\n"
        )
    # AMBER Lipid21 / Slipids
    return (
        "cutoff-scheme           = Verlet\n"
        "coulombtype             = PME\n"
        "rcoulomb                = 1.0\n"
        "vdwtype                 = Cut-off\n"
        "rvdw                    = 1.0\n"
        "DispCorr                = EnerPres\n"
    )


def _tcoupl_block(temperature: float, groups: Sequence[str]) -> str:
    grps = " ".join(groups)
    taus = " ".join(["1.0"] * len(groups))
    refs = " ".join([f"{temperature}"] * len(groups))
    return (
        "tcoupl                  = V-rescale\n"
        f"tc-grps                 = {grps}\n"
        f"tau-t                   = {taus}\n"
        f"ref-t                   = {refs}\n"
    )


def _pcoupl_block(kind: str) -> str:
    """Semiisotropic pressure coupling block. ``kind`` = barostat name or 'no'."""
    if kind == "no":
        return "pcoupl                  = no\n"
    return (
        f"pcoupl                  = {kind}\n"
        "pcoupltype              = semiisotropic\n"
        "ref-p                   = 1.0     1.0\n"
        "compressibility         = 4.5e-5  4.5e-5\n"
        "tau-p                   = 5.0\n"
        "refcoord-scaling        = com\n"
    )


_EM = """; Membrane energy minimization (PRISM)
integrator              = steep
emtol                   = 1000.0
emstep                  = 0.01
nsteps                  = 50000
nstlist                 = 10
{vdw}"""

_EQ = """; Membrane {stage} equilibration (PRISM)
integrator              = md
dt                      = 0.002
nsteps                  = {nsteps}
nstxout-compressed      = 5000
nstlog                  = 5000
nstenergy               = 5000
continuation            = {cont}
constraint-algorithm    = lincs
constraints             = h-bonds
lincs-iter              = 1
lincs-order             = 4
{vdw}{tcoupl}{pcoupl}gen-vel                 = {genvel}
gen-temp                = {temperature}
gen-seed                = -1
{posres}"""

_MD = """; Membrane production MD (PRISM)
integrator              = md
dt                      = 0.002
nsteps                  = {nsteps}
nstxout-compressed      = 50000
nstlog                  = 50000
nstenergy               = 50000
continuation            = yes
constraint-algorithm    = lincs
constraints             = h-bonds
lincs-iter              = 1
lincs-order             = 4
{vdw}{tcoupl}{pcoupl}gen-vel                 = no
"""


def write_membrane_mdps(
    out_dir: str,
    temperature: float = 303.15,
    ff_family: str = "amber",
    tc_groups: Sequence[str] = ("SOLU", "MEMB", "SOLV"),
    production_ns: float = 100.0,
    posres_define: str = "",
) -> dict:
    """Write the four-stage membrane MDP protocol into ``out_dir/mdps``.

    ``posres_define`` is the literal ``define`` line value (e.g. ``-DPOSRES``)
    and is emitted only when non-empty AND backed by matching
    ``#ifdef``-guarded ``[ position_restraints ]`` in the topology. It defaults
    to empty: PRISM does not yet generate the position-restraint include files,
    so emitting ``-DPOSRES*`` macros would be a silent no-op (no restraints).
    Generating genrestr-based restraints for the SOLU/MEMB groups is a planned
    next increment; until then the equilibration runs unrestrained (the system
    is already energy-minimised by PACKMOL-Memgen).

    Returns a mapping of stage -> file path.
    """
    mdp_dir = os.path.join(out_dir, "mdps")
    os.makedirs(mdp_dir, exist_ok=True)
    vdw = _vdw_block(ff_family)
    tcoupl = _tcoupl_block(temperature, tc_groups)
    define_block = f"define                  = {posres_define}\n" if posres_define else ""

    files = {}

    # EM (no temperature/pressure coupling)
    files["em"] = os.path.join(mdp_dir, "em.mdp")
    with open(files["em"], "w") as fh:
        fh.write(_EM.format(vdw=vdw))

    # NVT (velocities generated; restraints applied only if posres_define is set)
    files["nvt"] = os.path.join(mdp_dir, "nvt.mdp")
    with open(files["nvt"], "w") as fh:
        fh.write(_EQ.format(
            stage="NVT", nsteps=125000, cont="no", vdw=vdw, tcoupl=tcoupl,
            pcoupl=_pcoupl_block("no"), genvel="yes", temperature=temperature,
            posres=define_block,
        ))

    # NPT (semiisotropic C-rescale)
    files["npt"] = os.path.join(mdp_dir, "npt.mdp")
    with open(files["npt"], "w") as fh:
        fh.write(_EQ.format(
            stage="NPT", nsteps=250000, cont="yes", vdw=vdw, tcoupl=tcoupl,
            pcoupl=_pcoupl_block("C-rescale"), genvel="no", temperature=temperature,
            posres=define_block,
        ))

    # Production (Parrinello-Rahman, unrestrained)
    nsteps_prod = int(production_ns * 1000 / 0.002)
    files["md"] = os.path.join(mdp_dir, "md.mdp")
    with open(files["md"], "w") as fh:
        fh.write(_MD.format(
            nsteps=nsteps_prod, vdw=vdw, tcoupl=tcoupl,
            pcoupl=_pcoupl_block("Parrinello-Rahman"),
        ))

    return files
