# General settings
general:
  overwrite: false  # Whether to overwrite existing files

# Protein force field settings
forcefield:
  index: 3  # Default: amber14sb_OL15
  custom_forcefields:
    1: 
      name: "amber99sb"
      dir: "amber99sb.ff"
    2: 
      name: "amber99sb-ildn"
      dir: "amber99sb-ildn.ff"
    3: 
      name: "amber14sb_OL15"
      dir: "amber14sb_OL15_cufix_zn.ff"
    4: 
      name: "amber03"
      dir: "amber03.ff"
    5: 
      name: "amber96"
      dir: "amber96.ff"
    6: 
      name: "amber94"
      dir: "amber94.ff"
    7: 
      name: "charmm27"
      dir: "charmm27.ff"
    8: 
      name: "oplsaa"
      dir: "oplsaa.ff"

# Water model settings
water_model:
  index: 1  # Default: tip3p
  custom_water_models:
    1: 
      name: "tip3p"
    2: 
      name: "tip4p"
    3: 
      name: "spc"
    4: 
      name: "spce"
    5: 
      name: "none"

# Box settings
box:
  distance: 1.5  # Distance from solute to box edge (nm)
  shape: cubic   # Box shape: cubic, dodecahedron, or octahedron
  center: true   # Center the system in the box

# Simulation parameters
simulation:
  temperature: 310.0        # Temperature (K)
  pressure: 1.0            # Pressure (bar)
  pH: 7.0                  # pH for protonation states
  ligand_charge: 0         # Ligand net charge
  production_time_ns: 500  # Production simulation time (ns)
  dt: 0.002               # Time step (ps)
  equilibration_nvt_time_ps: 500  # NVT equilibration time (ps)
  equilibration_npt_time_ps: 500  # NPT equilibration time (ps)

# Ion settings
ions:
  neutral: true         # Neutralize the system
  concentration: 0.15   # Salt concentration (M)
  positive_ion: "NA"    # Positive ion type
  negative_ion: "CL"    # Negative ion type

# Constraint settings
constraints:
  algorithm: lincs      # Constraint algorithm: lincs or shake
  type: h-bonds        # Constraint type: none, h-bonds, or all-bonds
  lincs_iter: 1        # LINCS iterations
  lincs_order: 4       # LINCS order

# Energy minimization settings
energy_minimization:
  integrator: steep     # Minimization algorithm
  emtol: 200.0         # Energy tolerance (kJ/mol/nm)
  emstep: 0.01         # Initial step size (nm)
  nsteps: 10000        # Maximum number of steps

# Output settings
output:
  trajectory_interval_ps: 500  # Trajectory output interval (ps)
  energy_interval_ps: 10       # Energy output interval (ps)
  log_interval_ps: 10         # Log output interval (ps)
  compressed_trajectory: true  # Use compressed trajectory format (.xtc)

# Electrostatics settings
electrostatics:
  coulombtype: PME       # Electrostatics method
  rcoulomb: 1.0         # Coulomb cutoff (nm)
  pme_order: 4          # PME interpolation order
  fourierspacing: 0.16  # PME grid spacing (nm)

# Van der Waals settings
vdw:
  rvdw: 1.0            # VdW cutoff (nm)
  dispcorr: EnerPres   # Dispersion correction

# Temperature coupling
temperature_coupling:
  tcoupl: V-rescale    # Temperature coupling algorithm
  tc_grps: ["Protein", "Non-Protein"]  # Temperature coupling groups
  tau_t: [0.1, 0.1]    # Coupling time constants (ps)

# Pressure coupling
pressure_coupling:
  pcoupl: C-rescale    # Pressure coupling algorithm
  pcoupltype: isotropic  # Pressure coupling type
  tau_p: 1.0           # Coupling time constant (ps)
  compressibility: 4.5e-5  # Compressibility (bar^-1)
