# PMF Equilibration Configuration
# Based on PRISM main module structure for consistency

# Execution mode: 'local' or 'slurm'
execution_mode: "local"

# Local execution settings
local:
  cpus: 10
  gpu_id: 0
  ntmpi: 1
  ntomp: 10

# Slurm execution settings
slurm:
  partition: "gpu"
  cpus_per_task: 10
  time: "12:00:00"
  memory: "32G"
  gres: "gpu:1"
  conda_env: "prism_env"
  ntmpi: 1
  ntomp: 10

# Structure preparation parameters for PMF
structure_preparation:
  protein_selection: "Protein"       # Protein group selection
  ligand_selection: "resname UNL"    # Ligand group selection (modify as needed)
  pulling_direction: "z"             # Pulling direction (x, y, or z)
  box_padding: 1.5                   # Box padding in nm
  water_model: "tip3p"               # Water model
  positive_ion: "NA"                 # Positive ion type
  negative_ion: "CL"                 # Negative ion type
  ion_concentration: 0.15            # Salt concentration in M

# Simulation parameters (following PRISM structure)
simulation:
  temperature: 300                    # Temperature (K)
  pressure: 1.0                      # Pressure (bar)
  dt: 0.002                         # Time step (ps)
  equilibration_nvt_time_ps: 1000   # NVT equilibration time (ps)
  equilibration_npt_time_ps: 2000   # NPT equilibration time (ps)

# Energy minimization settings
energy_minimization:
  integrator: steep                 # Minimization algorithm
  emtol: 10.0                      # Convergence criterion (kJ/mol/nm)
  emstep: 0.01                     # Initial step size
  nsteps: 50000                    # Maximum steps
  maxwarn: 3                       # Maximum warnings allowed

# Constraint settings
constraints:
  algorithm: lincs                 # Constraint algorithm
  type: h-bonds                   # Constrain: none, h-bonds, all-bonds
  lincs_iter: 1                   # LINCS iterations
  lincs_order: 4                  # LINCS order

# Electrostatics settings
electrostatics:
  coulombtype: PME                # Electrostatics method
  rcoulomb: 1.0                  # Coulomb cutoff (nm)
  pme_order: 4                   # PME interpolation order
  fourierspacing: 0.16           # Grid spacing for FFT (nm)

# Van der Waals settings
vdw:
  rvdw: 1.0                      # VdW cutoff (nm)
  dispcorr: EnerPres             # Dispersion correction

# Temperature coupling
temperature_coupling:
  tcoupl: V-rescale              # Temperature coupling algorithm
  tc_grps:                       # Coupling groups
    - system
  tau_t:                         # Coupling time constants (ps)
    - 0.1

# Pressure coupling
pressure_coupling:
  pcoupl: Parrinello-Rahman      # Pressure coupling algorithm
  pcoupltype: isotropic          # Pressure coupling type
  tau_p: 2.0                     # Coupling time constant (ps)
  compressibility: 4.5e-05       # Compressibility (bar^-1)

# Output settings
output:
  energy_interval_ps: 1.0        # Save energy every X ps (converted to nsteps)
  log_interval_ps: 1.0           # Log output every X ps (converted to nsteps)
  trajectory_interval_ps: 5.0    # Save trajectory every X ps (compressed)

# Neighbor searching
neighbor_search:
  cutoff_scheme: Verlet          # Cutoff scheme
  ns_type: grid                  # Neighbor search type
  nstlist: 10                    # Frequency to update neighbor list

# Periodic boundary conditions
pbc:
  type: xyz                      # PBC type

# Velocity generation (for NVT)
velocity_generation:
  gen_vel_nvt: true              # Generate velocities for NVT
  gen_temp_seed: -1              # Random seed (-1 for random)